-- SELECT * FROM DWA.STAT_TEST_BRIGHTICS
SELECT OFMN
     , SIDO_CD
	 , SIGG_CD
	 , SIDO_CD||SIGG_CD AS SGG_CD
	 , FSTT_SEPR_DTC    
FROM DWA.TB_MTA_OBFF_RSAN_VABL
WHERE 1 = 1
AND BASE_DE_CD = '{BASE_DE_CD}'
ORDER BY OFMN
