-- SELECT * FROM DWA.STAT_TEST_BRIGHTICS
SELECT OFMN
     , PRMS_DE
     , FIRE_RCPT_DE
     , FRST_FIRE_OCCR_DE
     , BDNG_PSVT_YCNT
     , BEUP_CNT
     , FIRE_SFIV_HIST_AT
     , BDNG_FORM_SE_CDN
     , BDNG_RF_SE_CDN
     , BDNG_STRC_SE_CDN
     , BDNG_MPP_CDN
     , SIDO_CD
     , SFMG_GRAD_CD
     , FINS_SSCR_HIST_AT    -- NOW_FINS_SSCR_AT
     , FFN_ADTN_CO
     , DGST_MNGE_TRGT_CNT     
FROM DWA.TB_MTA_OBFF_RSAN_VABL
WHERE 1 = 1
AND BASE_DE_CD = '{BASE_DE_CD}'
-- AND PRMS_DE IS NOT NULL
-- AND NVL(FIRE_SFIV_DE,1) < NVL(SUBSTR(FIRE_RCPT_DE,1,8),NVL(FIRE_SFIV_DE,1)+1)
-- AND ROWNUM < 1000    -- 너무 오래걸려서 임시 처리
ORDER BY OFMN