SELECT A.OFMN
     , A.PRMS_DE
     , A.FIRE_RCPT_DE
     , A.FRST_FIRE_OCCR_DE
     , A.BDNG_PSVT_YCNT
     , A.BEUP_CNT
     , A.FIRE_SFIV_HIST_AT
     , A.BDNG_FORM_SE_CDN
     , A.BDNG_RF_SE_CDN
     , A.BDNG_STRC_SE_CDN
     , A.BDNG_MPP_CDN
     , A.SIDO_CD
     , A.SFMG_GRAD_CD
     , A.NOW_FINS_SSCR_AT
     , A.FFN_ADTN_CO
     , A.DGST_MNGE_TRGT_CNT     
FROM DWA.TB_MTA_OBFF_RSAN_VABL	A
INNER JOIN (
	SELECT B1.OFMN
	FROM TB_WVD_OFFS B1
	WHERE 1=1
	AND   OFFS_TY_CD = '1000000001'
	AND   USE_AT <> 'N'
	AND   BF_BDNG_NO IS NOT NULL
) B
ON A.OFMN = B.OFMN
WHERE 1 = 1
AND A.BASE_DE_CD = '{BASE_DE_CD}'
AND A.PRMS_DE IS NOT NULL
-- AND NVL(A.FIRE_SFIV_DE,1) < NVL(SUBSTR(A.FIRE_RCPT_DE,1,8),NVL(A.FIRE_SFIV_DE,1)+1)


-- -- SELECT * FROM DWA.STAT_TEST_BRIGHTICS
-- SELECT OFMN
--      , PRMS_DE
--      , FIRE_RCPT_DE
--      , FRST_FIRE_OCCR_DE
--      , BDNG_PSVT_YCNT
--      , BEUP_CNT
--      , FIRE_SFIV_HIST_AT
--      , BDNG_FORM_SE_CDN
--      , BDNG_RF_SE_CDN
--      , BDNG_STRC_SE_CDN
--      , BDNG_MPP_CDN
--      , SIDO_CD
--      , SFMG_GRAD_CD
--      , NOW_FINS_SSCR_AT
--      , FFN_ADTN_CO
--      , DGST_MNGE_TRGT_CNT     
-- FROM DWA.TB_MTA_OBFF_RSAN_VABL
-- WHERE 1 = 1
-- AND BASE_DE_CD = '{BASE_DE_CD}'
-- AND PRMS_DE IS NOT NULL
-- AND NVL(FIRE_SFIV_DE,1) < NVL(SUBSTR(FIRE_RCPT_DE,1,8),NVL(FIRE_SFIV_DE,1)+1)
-- AND ROWNUM < 5000    -- 너무 오래걸려서 임시 처리