-- -- 변경 2차
-- SELECT OFMN
--      , BDNG_FORM_SE_CDN
--      , BDNG_RF_SE_CDN
--      , BDNG_STRC_SE_CDN
--      , BDNG_MPP_CDN
--      , FFN_ADTN_CO    -- 변경
--      , BEUP_CNT    -- 변경
--      , DGST_MNGE_TRGT_CNT    -- 변경
--      , PRTY_DMGE_AMT -- 변경
-- FROM DWA.TB_MTA_OBFF_RSAN_VABL
-- WHERE 1 = 1
-- AND BASE_DE_CD = '{BASE_DE_CD}'
-- -- AND ROWNUM < 5000    -- 너무 오래걸려서 임시 처리



-- 임시 (21/02/08)
SELECT DISTINCT A.OFMN
	, A.FFN_CO
	, A.BEUP_CO
	, A.DGST_CO
	, A.BDNG_MPP_NM
	, A.BDNG_FORM_SE_NM
	, A.BDNG_STRC_SE_NM
	, A.BDNG_RF_SE_NM
    , A.ALL_AR
    , A.TTL_FLRC
	, A.FSTT_DTC
	, MAX(A.PRTY_DMGE_SBSM_AMT) OVER (PARTITION BY A.OFMN) AS PRTY_DMGE_SBSM_AMT
	, MAX(A.TTL_PCNT) OVER (PARTITION BY A.OFMN) AS TTL_PCNT
-- 	, TO_NUMBER(A.FFA_PLAN_AT) as FFA_PLAN_AT  -- 없어서 주석처리
	--, A.FIRE_OCCR_NO
FROM (
SELECT A.OFMN
	 , NVL(FFN_CO, 0) AS FFN_CO	 
	 , NVL(A.BEUP_CO,0) AS BEUP_CO
	 , NVL(A.DGST_CO,0) AS DGST_CO
    , A.ALL_AR
    , A.TTL_FLRC
	 , NVL((SELECT cdn FROM tb_wvd_cmmn_cd WHERE cd = BDNG_MPP_CD),(SELECT GR_cdn FROM tb_wvd_cmmn_GR_cd WHERE GR_cd = BDNG_MPP_CD)) AS BDNG_MPP_NM
 	 , (SELECT cdn FROM tb_wvd_cmmn_cd WHERE cd = BDNG_FORM_SE_CD) AS BDNG_FORM_SE_NM
	 , (SELECT cdn FROM tb_wvd_cmmn_cd WHERE cd = BDNG_STRC_SE_CD) AS BDNG_STRC_SE_NM 
	 , (SELECT cdn FROM tb_wvd_cmmn_cd WHERE cd = BDNG_RF_SE_CD) AS BDNG_RF_SE_NM
	 , C.PRTY_DMGE_SBSM_AMT -- 재산피해소계금액
	 , NVL(C.DPRS_PCNT,0) + NVL(C.IJPS_PCNT,0) + NVL(C.DSSR_PCNT, 0) AS TTL_PCNT -- 인명피해
	 , C.FSTT_DTC -- 소방서 거리
-- 	 , A.FFA_PLAN_AT  -- 없어서 주석처리
	 , RANK() OVER (PARTITION BY C.OFMN ORDER BY C.FIRE_OCCR_DE) as FIRE_OCCR_NO
FROM TB_MTA_FRIG C
LEFT OUTER JOIN DWA.WVD_LIST A
ON C.OFMN = A.OFMN
LEFT OUTER JOIN DWA.WVN_LIST B
ON C.OFMN = B.OFMN
WHERE A.OFMN IS NOT NULL
) A
WHERE A.FIRE_OCCR_NO = 1




-- AND FFN_ADTN_CO IS NOT NULL
-- AND BEUP_CNT IS NOT NULL
-- AND DGST_MNGE_TRGT_CNT IS NOT NULL

-- -- 변경 1차
-- SELECT * 
--   FROM DWA.STAT_TEST_BRIGHTICS
--  WHERE 1 = 1
--    AND PRTY_DMGE_SBSM_AMT IS NOT NULL

-- 기존
-- SELECT DISTINCT A.OFMN
-- 	, A.FFN_CO
-- 	, A.BEUP_CO
-- 	, A.DGST_CO
-- 	, A.BDNG_MPP_NM
-- 	, A.BDNG_FORM_SE_NM
-- 	, A.BDNG_STRC_SE_NM
-- 	, A.BDNG_RF_SE_NM
--     , A.ALL_AR
--     , A.TTL_FLRC
-- 	, A.FSTT_DTC
-- 	, MAX(A.PRTY_DMGE_SBSM_AMT) OVER (PARTITION BY A.OFMN) AS PRTY_DMGE_SBSM_AMT
-- 	, MAX(A.TTL_PCNT) OVER (PARTITION BY A.OFMN) AS TTL_PCNT
-- -- 	, TO_NUMBER(A.FFA_PLAN_AT) as FFA_PLAN_AT  -- 없어서 주석처리
-- 	--, A.FIRE_OCCR_NO
-- FROM (
-- SELECT A.OFMN
-- 	 , NVL(FFN_CO, 0) AS FFN_CO	 
-- 	 , NVL(A.BEUP_CO,0) AS BEUP_CO
-- 	 , NVL(A.DGST_CO,0) AS DGST_CO
--     , A.ALL_AR
--     , A.TTL_FLRC
-- 	 , NVL((SELECT cdn FROM tb_wvd_cmmn_cd WHERE cd = BDNG_MPP_CD),(SELECT GR_cdn FROM tb_wvd_cmmn_GR_cd WHERE GR_cd = BDNG_MPP_CD)) AS BDNG_MPP_NM
--  	 , (SELECT cdn FROM tb_wvd_cmmn_cd WHERE cd = BDNG_FORM_SE_CD) AS BDNG_FORM_SE_NM
-- 	 , (SELECT cdn FROM tb_wvd_cmmn_cd WHERE cd = BDNG_STRC_SE_CD) AS BDNG_STRC_SE_NM 
-- 	 , (SELECT cdn FROM tb_wvd_cmmn_cd WHERE cd = BDNG_RF_SE_CD) AS BDNG_RF_SE_NM
-- 	 , C.PRTY_DMGE_SBSM_AMT -- 재산피해소계금액
-- 	 , NVL(C.DPRS_PCNT,0) + NVL(C.IJPS_PCNT,0) + NVL(C.DSSR_PCNT, 0) AS TTL_PCNT -- 인명피해
-- 	 , C.FSTT_DTC -- 소방서 거리
-- -- 	 , A.FFA_PLAN_AT  -- 없어서 주석처리
-- 	 , RANK() OVER (PARTITION BY C.OFMN ORDER BY C.FIRE_OCCR_DE) as FIRE_OCCR_NO
-- FROM TB_MTA_FRIG C
-- LEFT OUTER JOIN DWA.WVD_LIST A
-- ON C.OFMN = A.OFMN
-- LEFT OUTER JOIN DWA.WVN_LIST B
-- ON C.OFMN = B.OFMN
-- WHERE A.OFMN IS NOT NULL
-- ) A
-- WHERE A.FIRE_OCCR_NO = 1